--- 
- hosts: dummy
  become: yes
  vars: 
    - htmlloc: /var/www/html
  tasks: 
    - wait_for: port=22 delay=30

    - name: Install httplib2
      apt: pkg=python-httplib2 state=installed update_cache=true

    - name: Install apache2
      apt: pkg=apache2 state=installed update_cache=true
      register: apache2installed
      notify:
       - Start apache2

    - name: Create index
      when: apache2installed|success
      copy: src=/Users/madams/Documents/lab/stelligent/index.html dest=/var/www/html/index.html mode=755  owner=root group=root
      notify:
        - Restart apache2

    - action: uri url=http://localhost return_content=yes
      register: webpage

    - fail: msg='web content not loaded properly'
      when: "'Automation for the People' not in webpage.content"

  handlers:
    - name: Start apache2
      service: name=apache2 state=started

    - name: Restart apache2
      service: name=apache2 state=restarted

    - name: reload apache2
      service: name=apache2 state=reloaded

